# Generated by Django 3.1.2 on 2020-12-03 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuis', '0003_auto_20201203_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
