# Generated by Django 3.1.2 on 2020-12-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuis', '0006_auto_20201204_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
