# Generated by Django 3.1.2 on 2020-12-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuis', '0007_auto_20201205_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='judul',
            field=models.CharField(max_length=100),
        ),
    ]
