# Generated by Django 3.1.2 on 2020-12-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuis', '0008_auto_20201206_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='judul',
            field=models.CharField(max_length=1000),
        ),
    ]
